apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: public.ecr.aws/y5u7j3p0/user:latest
          ports:
            - containerPort: 5002
          envFrom:
            - secretRef:
                name: mongo-secret